/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

/**
 *
 * @author alexandercarrero
 */
public class VistaInicio extends javax.swing.JFrame {

    /**
     * Creates new form VistaInicio2
     */
    public VistaInicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menu_productos_inicio = new javax.swing.JMenuItem();
        menu_clientes_inicio = new javax.swing.JMenuItem();
        menu_vendedores_inicio = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menu_facturas_inicio = new javax.swing.JMenuItem();
        menu_ventas_inicio = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        menu_ventasTotales_inicio = new javax.swing.JMenuItem();
        menu_gestionVendedores_inicio = new javax.swing.JMenuItem();
        menu_tipoPago_inicio = new javax.swing.JMenuItem();
        salir_inicio = new javax.swing.JMenu();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Comercio Cachivaches");

        jMenu1.setText("Gestión Datos");

        menu_productos_inicio.setText("Productos");
        menu_productos_inicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_productos_inicioActionPerformed(evt);
            }
        });
        jMenu1.add(menu_productos_inicio);

        menu_clientes_inicio.setText("Clientes");
        jMenu1.add(menu_clientes_inicio);

        menu_vendedores_inicio.setText("Vendedores");
        jMenu1.add(menu_vendedores_inicio);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Ventas");

        menu_facturas_inicio.setText("Facturas");
        menu_facturas_inicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_facturas_inicioActionPerformed(evt);
            }
        });
        jMenu2.add(menu_facturas_inicio);

        menu_ventas_inicio.setText("Ventas");
        jMenu2.add(menu_ventas_inicio);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Informes");

        menu_ventasTotales_inicio.setText("Ventas Totales");
        jMenu3.add(menu_ventasTotales_inicio);

        menu_gestionVendedores_inicio.setText("Gestión Vendedores");
        jMenu3.add(menu_gestionVendedores_inicio);

        menu_tipoPago_inicio.setText("Tipo de Pago");
        jMenu3.add(menu_tipoPago_inicio);

        jMenuBar1.add(jMenu3);

        salir_inicio.setText("Salir");
        jMenuBar1.add(salir_inicio);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 276, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menu_productos_inicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_productos_inicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menu_productos_inicioActionPerformed

    private void menu_facturas_inicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_facturas_inicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menu_facturas_inicioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaInicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    public javax.swing.JMenuItem menu_clientes_inicio;
    public javax.swing.JMenuItem menu_facturas_inicio;
    public javax.swing.JMenuItem menu_gestionVendedores_inicio;
    public javax.swing.JMenuItem menu_productos_inicio;
    public javax.swing.JMenuItem menu_tipoPago_inicio;
    public javax.swing.JMenuItem menu_vendedores_inicio;
    public javax.swing.JMenuItem menu_ventasTotales_inicio;
    public javax.swing.JMenuItem menu_ventas_inicio;
    public javax.swing.JMenu salir_inicio;
    // End of variables declaration//GEN-END:variables
}
